# Generated by Django 2.2.5 on 2019-10-05 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getData', '0003_auto_20191005_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneuser',
            name='otp',
            field=models.IntegerField(default=92318),
        ),
    ]
