# Generated by Django 2.2.5 on 2019-10-05 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getData', '0004_auto_20191005_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneuser',
            name='otp',
            field=models.IntegerField(default=54547),
        ),
    ]
