# Generated by Django 2.2.5 on 2019-10-05 05:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('getData', '0005_auto_20191005_0635'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptModel',
            fields=[
                ('receipt_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('order_id', models.CharField(blank=True, max_length=100)),
                ('payment_id', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='phoneuser',
            name='otp',
            field=models.IntegerField(default=62191),
        ),
    ]
