# Generated by Django 2.2.5 on 2019-10-05 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getData', '0006_auto_20191005_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneuser',
            name='otp',
            field=models.IntegerField(default=17902),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/media'),
        ),
    ]
